when:
  - event: push
    branch: main

steps:
  - name: build
    image: alpine
    commands:
      - echo "This is the build step"
      - echo "binary-data-123" > executable
    runs_on: [manual]
  - name: a-test-step
    image: golang:1.16
    commands:
      - echo "Testing ..."
      - ./executable
    runs_on: [manual]
